language: ruby
rvm:
  - '2.0.0'
bundler_args: --without production
before_script:
  - cp config/database.yml.dist config/database.yml
  - psql -c 'create database ledger_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake
